imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    # FIXME: should this be configurable via parameters.yml?
    locale: en

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret: "%secret%"

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
