imports:
    - { resource: parameters.yml }

parameters:
    # FIXME: should this be configurable via parameters.yml?
    locale: en

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret: "%secret%"
