imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    # FIXME: should this be configurable via parameters.yml?
    locale: en

# Framework configuration
framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
    default_locale: "%locale%"

# Twig configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# SwiftMailer configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
