imports:
    - { resource: config.yml }

# Framework configuration
framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# Contao configuration
contao:
    pretty_error_screens: false

# Web profiler configuration
web_profiler:
    toolbar: true
    intercept_redirects: false
